### ISSUE TITLE
Consider using dictionary spec for the value

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/correlation-context#15]
https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-08#section-3.1

**Comment by SergeyKanzhelev** [comment]
status: https://datatracker.ietf.org/doc/draft-ietf-httpbis-header-structure/

**Comment by mwear** [comment]
I think this is the most current version of that spec: https://tools.ietf.org/id/draft-ietf-httpbis-header-structure-15.html#rfc.section.3.2. Not sure what, if anything, has changed between this one and the one liked above.

Also possibly of interest. The state of the specification is: `In WG Last Call`. Here's a document that indicates what that means: https://datatracker.ietf.org/help/state/draft/ietf.

**Comment by dyladan** [comment]
> Not sure what, if anything, has changed between this one and the one liked above.

Nothing changed. Sergey linked to the version tracker which shows the latest by default. You linked to the rendered copy of a particular version (which also happens to be the latest).

**Comment by mwear** [comment]
The first comment has a direct link to version 8, which is dated.

**Comment by danielkhan** [comment]
In our virtual F2F workshop we agreed to stick to the simple `key=value;options` format that is currently also specified in the working draft. This will be proposed in a new PR. I will close this issue for now.
