### ISSUE TITLE
Support for a type property of a Correlation Context value

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/correlation-context#3]
Copy from https://github.com/w3c/trace-context/issues/22

Some tracing vendors support types for the context properties. We can add `type` property to allow an explicit type specification. Something like this:

### Boolean
 
Binary flag. Supported values `1` for true and `0` for false.
 
**Examples**:
 
```
IsAuthenticated=1;type=bool
IsAuthenticated=0;type=bool
```
 
### Number
 
Numeric value as described in IEEE 754-2008 binary64 (double precision) numbers [IEEE754](https://en.wikipedia.org/wiki/Double-precision_floating-point_format).
 
**Examples**:
 
```
ExposurePercentage=33.33;type=number
Step=10;type=number
```

**Comment by yurishkuro** [comment]
I would avoid strong types. HTTP headers themselves don't have types, what is special about correlation context that _requires_ types?

**Comment by SergeyKanzhelev** [comment]
It was discussed today at workshop and there were no scenarios suggested that would require protocol to support types. Let's re-open when the feature will be requested
