### ISSUE TITLE
Need to find a place for standard test suite

### ISSUE THREAD

**Issue by reyang** [w3c/correlation-context#9]
I remember we want to move the [tracecontext test suite ](https://github.com/w3c/trace-context/tree/master/test)to a separate repo in order to keep the spec repo clean (e.g. we don't want to go through the spec updating process each time we improve the test cases).

Now we have a chance to do it in correlation context, where should we put the test? @bogdandrutu @SergeyKanzhelev

**Comment by reyang** [comment]
@plehegar I'd like to get your suggestion.

**Comment by plehegar** [comment]
I can create a dedicated repo for it, with the proper LICENSE.md (which is a different one from the spec).

**Comment by SergeyKanzhelev** [comment]
Decision was to keep it in the same repo.
